### ISSUE TITLE
增加查询城市选项，默认到ip所在城市

### ISSUE THREAD

**Issue by ejbiva1** [ejbiva1/joblink#22]

**Comment by modin-yu** [comment]
修改完成，代码已提交，等在测试服务器上通过验收后即可关闭。

**Comment by modin-yu** [comment]
session.get("visitor_ip"); 可以获得当前用户访问ip地址
session.get("visitor_city"); 可以获得当前用户访问ip地址所对应的城市
session.get("user").getCity() 可以获得当前登录用户的所在城市
