### ISSUE TITLE
需要一个内部使用的界面用来管理目前所有的职位申请

### ISSUE THREAD

**Issue by ejbiva1** [ejbiva1/joblink#40]
目前有多少人在申请职位是不知道的，需要提供一个界面知道谁在申请谁的什么职位。状态如何，此功能仅供内部管理使用

**Comment by ejbiva1** [comment]
JSP:alljobapplier.jsp

**Comment by modin-yu** [comment]
访问调用findAllApplicationList.do
需要传如下参数，若参数为空则表示不查询该条件

int pageNo 不传或为空则默认为第一页
Integer status 状态
String employerName 企业雇主名称
String city 职位所在城市
Boolean ifInterview 是否提供面试 0不需要面试，1需要面试
Boolean ifOpen 1 职位开放 0已关闭
Boolean ifValid  1 职位正常 0非法职位(发布者已切换其他雇主)
Boolean ifEffective 1职位有效 0职位已过期失效
