### ISSUE TITLE
需要一个界面显示所有的注册用户

### ISSUE THREAD

**Issue by ejbiva1** [ejbiva1/joblink#44]

**Comment by modin-yu** [comment]
访问调用findAllUserList.do
需要传如下参数，若参数为空则表示不查询该条件

int pageNo 不传或为空则默认为第一页
String userName 用户登录名(模糊查询)
String city 用户所在城市
String employerName 用户所属雇主名称(模糊查询)
String title 用户当前职位(模糊查询)
Integer experienceAge 用户工作经验年限(自然数)
Integer educationLevel 用户教育程度  1 大专 2 本科  3 硕士 4 博士
Boolean ifTobeSearched 用户是否愿意被招聘方搜索到

**Comment by ejbiva1** [comment]
VUser需要一个注册日期字段

**Comment by modin-yu** [comment]
页面翻页有问题

**Comment by modin-yu** [comment]
在用户列表中点击用户查看详情，详情页面报错。
